import type { Metadata } from "next";
import { Almarai } from "next/font/google";

import "./globals.css";

const almarai = Almarai({
  weight: ['300', '400', '700', '800'], // Available weights
  subsets: ['arabic'], // Supports Arabic script
  display: 'swap', // Better loading behavior
  variable: '--font-almarai', // CSS variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${almarai.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
